import { Exercise } from "@/types";

export const exercises: Exercise[] = [
  // Warm-up
  {
    id: "treadmill-walk",
    name: "Treadmill Walk",
    category: "warmup",
    muscles: ["Full body", "Cardiovascular"],
    equipment: "Treadmill",
    cues: ["3-3.5 mph", "Relaxed shoulders", "Natural arm swing"],
    mistakes: ["Holding the rails", "Leaning back"],
    backFriendlyAlternativeId: null,
  },
  {
    id: "cat-camel",
    name: "Cat-Camel",
    category: "warmup",
    muscles: ["Spine mobility"],
    equipment: "None",
    cues: ["Move slowly", "Round then arch through the whole spine", "Breathe with the motion"],
    mistakes: ["Rushing the reps", "Moving only through the lower back"],
    backFriendlyAlternativeId: null,
  },
  {
    id: "bird-dog",
    name: "Bird Dog",
    category: "warmup",
    muscles: ["Core", "Glutes", "Spinal stability"],
    equipment: "None",
    cues: ["Brace core first", "Extend opposite arm and leg", "Keep hips level, no rotation"],
    mistakes: ["Arching the low back", "Rushing instead of controlling the reach"],
    backFriendlyAlternativeId: null,
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    category: "warmup",
    muscles: ["Glutes", "Hamstrings"],
    equipment: "None",
    cues: ["Push through heels", "Squeeze glutes at the top", "Avoid over-arching the back"],
    mistakes: ["Overextending the lower back", "Pushing through the toes"],
    backFriendlyAlternativeId: null,
  },
  {
    id: "bodyweight-squat",
    name: "Bodyweight Squat",
    category: "warmup",
    muscles: ["Quads", "Glutes"],
    equipment: "None",
    cues: ["Sit hips back and down", "Chest tall", "Knees track over toes"],
    mistakes: ["Knees collapsing inward", "Heels lifting off the floor"],
    backFriendlyAlternativeId: null,
  },
  {
    id: "band-pull-apart",
    name: "Band Pull-Apart",
    category: "warmup",
    muscles: ["Rear delts", "Upper back"],
    equipment: "Resistance band",
    cues: ["Arms straight", "Squeeze shoulder blades together", "Control the return"],
    mistakes: ["Shrugging shoulders up", "Using momentum"],
    backFriendlyAlternativeId: null,
  },

  // Strength
  {
    id: "leg-press",
    name: "Leg Press",
    category: "strength",
    muscles: ["Quads", "Glutes", "Hamstrings"],
    equipment: "Leg press machine",
    cues: ["Feet shoulder-width on platform", "Drive through the whole foot", "Don't lock knees out hard at the top"],
    mistakes: ["Letting knees cave in", "Lower back rounding off the pad at the bottom"],
    backFriendlyAlternativeId: "goblet-squat",
    backFriendlyNote: "Lower back support built in — usually the safest heavy leg movement post-surgery.",
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    category: "strength",
    muscles: ["Quads", "Glutes", "Core"],
    equipment: "Dumbbell or kettlebell",
    cues: ["Brace first", "Keep chest tall", "Sit between your knees", "Drive through the whole foot"],
    mistakes: ["Knees collapsing inward", "Rounding the back"],
    backFriendlyAlternativeId: "leg-press",
  },
  {
    id: "db-bench-press",
    name: "Dumbbell Bench Press",
    category: "strength",
    muscles: ["Chest", "Triceps", "Shoulders"],
    equipment: "Dumbbells, bench",
    cues: ["Feet flat on the floor", "Shoulder blades pulled back and down", "Lower with control"],
    mistakes: ["Flaring elbows to 90°", "Bouncing the weights off the chest"],
    backFriendlyAlternativeId: "machine-chest-press",
  },
  {
    id: "incline-db-press",
    name: "Incline Dumbbell Press",
    category: "strength",
    muscles: ["Upper chest", "Shoulders", "Triceps"],
    equipment: "Dumbbells, incline bench",
    cues: ["30-45° incline", "Drive dumbbells up and slightly in", "Control the descent"],
    mistakes: ["Setting the incline too steep", "Half reps"],
    backFriendlyAlternativeId: "machine-chest-press",
  },
  {
    id: "machine-chest-press",
    name: "Machine Chest Press",
    category: "strength",
    muscles: ["Chest", "Triceps", "Shoulders"],
    equipment: "Chest press machine",
    cues: ["Seat height so handles align with mid-chest", "Full back support", "Control both directions"],
    mistakes: ["Seat set too low or high", "Slamming the weight stack"],
    backFriendlyAlternativeId: null,
  },
  {
    id: "chest-supported-row",
    name: "Chest-Supported Row",
    category: "strength",
    muscles: ["Upper back", "Lats", "Rear delts"],
    equipment: "Chest-supported row machine or incline bench + dumbbells",
    cues: ["Chest pinned to the pad", "Pull elbows back, not up", "Squeeze shoulder blades together"],
    mistakes: ["Using momentum off the pad", "Shrugging instead of rowing"],
    backFriendlyAlternativeId: null,
    backFriendlyNote: "Removes lower-back load entirely — a great default row for you.",
  },
  {
    id: "seated-cable-row",
    name: "Seated Cable Row",
    category: "strength",
    muscles: ["Upper back", "Lats", "Biceps"],
    equipment: "Cable row machine",
    cues: ["Sit tall, chest up", "Drive elbows back", "Avoid rocking the torso"],
    mistakes: ["Rounding the back to reach", "Yanking with momentum"],
    backFriendlyAlternativeId: "chest-supported-row",
  },
  {
    id: "cable-row",
    name: "Cable Row",
    category: "strength",
    muscles: ["Upper back", "Lats"],
    equipment: "Cable machine",
    cues: ["Neutral spine throughout", "Pull to the lower ribs", "Slow, controlled return"],
    mistakes: ["Leaning back excessively to move more weight"],
    backFriendlyAlternativeId: "chest-supported-row",
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    category: "strength",
    muscles: ["Lats", "Biceps", "Upper back"],
    equipment: "Cable pulldown machine",
    cues: ["Pull to upper chest", "Lead with the elbows", "Control the weight back up"],
    mistakes: ["Leaning back too far", "Using body momentum to yank the bar down"],
    backFriendlyAlternativeId: null,
  },
  {
    id: "rdl-dumbbell",
    name: "Romanian Deadlift (Dumbbells)",
    category: "strength",
    muscles: ["Hamstrings", "Glutes"],
    equipment: "Dumbbells",
    cues: ["Brace first", "Keep dumbbells close to the legs", "Soft knees", "Neutral spine, hinge from the hips"],
    mistakes: ["Rounding the lower back", "Letting the weights drift away from the body"],
    backFriendlyAlternativeId: "cable-pull-through",
    backFriendlyNote: "Keep the weight light and the range of motion short if your back is off that day.",
  },
  {
    id: "cable-pull-through",
    name: "Cable Pull-Through",
    category: "strength",
    muscles: ["Hamstrings", "Glutes"],
    equipment: "Cable machine, rope attachment",
    cues: ["Hinge at the hips, not the knees", "Squeeze glutes to stand tall", "Keep the spine neutral"],
    mistakes: ["Squatting the movement instead of hinging"],
    backFriendlyAlternativeId: null,
    backFriendlyNote: "Cable tension is more forgiving on the spine than a loaded hinge — good back-flare substitute.",
  },
  {
    id: "split-squat",
    name: "Split Squat",
    category: "strength",
    muscles: ["Quads", "Glutes"],
    equipment: "Bodyweight or dumbbells",
    cues: ["Long enough stance for a 90° front knee", "Torso upright", "Control the descent"],
    mistakes: ["Front knee traveling past the toes aggressively", "Stance too short"],
    backFriendlyAlternativeId: "step-ups",
  },
  {
    id: "step-ups",
    name: "Step-Ups",
    category: "strength",
    muscles: ["Quads", "Glutes"],
    equipment: "Box or bench, dumbbells optional",
    cues: ["Drive through the whole foot on the box", "Stand fully tall at the top", "Control the way down"],
    mistakes: ["Pushing off the bottom leg instead of the top leg"],
    backFriendlyAlternativeId: "split-squat",
  },
  {
    id: "hack-squat",
    name: "Hack Squat (Machine)",
    category: "strength",
    muscles: ["Quads", "Glutes"],
    equipment: "Hack squat machine",
    cues: ["Feet mid-platform", "Full back support against the pad", "Controlled depth"],
    mistakes: ["Going deeper than feels comfortable on the back", "Bouncing at the bottom"],
    backFriendlyAlternativeId: "leg-press",
  },
  {
    id: "face-pulls",
    name: "Face Pulls",
    category: "strength",
    muscles: ["Rear delts", "Upper back", "Rotator cuff"],
    equipment: "Cable machine, rope attachment",
    cues: ["Pull to eye level", "Rotate hands so thumbs point back at the top", "Lead with the elbows high"],
    mistakes: ["Using too much weight and turning it into a row"],
    backFriendlyAlternativeId: null,
  },
  {
    id: "pallof-press",
    name: "Pallof Press",
    category: "core",
    muscles: ["Core (anti-rotation)"],
    equipment: "Cable or band",
    cues: ["Press straight out from the chest", "Resist rotating toward the anchor", "Breathe, don't hold your breath"],
    mistakes: ["Letting the hips rotate toward the machine"],
    backFriendlyAlternativeId: null,
  },
  {
    id: "plank",
    name: "Plank",
    category: "core",
    muscles: ["Core", "Shoulders"],
    equipment: "None",
    cues: ["Straight line from head to heels", "Squeeze glutes and brace core", "Breathe steadily"],
    mistakes: ["Hips sagging or piking up", "Holding breath"],
    backFriendlyAlternativeId: "side-plank",
  },
  {
    id: "side-plank",
    name: "Side Plank",
    category: "core",
    muscles: ["Obliques", "Core"],
    equipment: "None",
    cues: ["Stack hips and shoulders", "Straight line head to feet", "Brace, don't sag"],
    mistakes: ["Letting the hips drop"],
    backFriendlyAlternativeId: null,
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    category: "core",
    muscles: ["Core", "Hip flexors"],
    equipment: "None",
    cues: ["Press low back gently into the floor", "Move opposite arm and leg slowly", "Exhale on the reach"],
    mistakes: ["Letting the low back arch off the floor"],
    backFriendlyAlternativeId: null,
  },

  // Carries / finishers
  {
    id: "farmer-carry",
    name: "Farmer Carries",
    category: "carry",
    muscles: ["Grip", "Core", "Traps", "Full body"],
    equipment: "Dumbbells or kettlebells",
    cues: ["Stand tall, shoulders back", "Short, controlled steps", "Brace core the whole way"],
    mistakes: ["Leaning to one side", "Shrugging the shoulders up toward the ears"],
    backFriendlyAlternativeId: "suitcase-carry",
  },
  {
    id: "suitcase-carry",
    name: "Suitcase Carry",
    category: "carry",
    muscles: ["Obliques", "Grip", "Core"],
    equipment: "One dumbbell or kettlebell",
    cues: ["Resist leaning toward the loaded side", "Tall posture", "Controlled, even steps"],
    mistakes: ["Letting the torso tilt toward the weight"],
    backFriendlyAlternativeId: "farmer-carry",
  },
];

export function getExerciseById(id: string): Exercise | undefined {
  return exercises.find((e) => e.id === id);
}
